name: Discord Webhook Test

on: [push]

jobs:
  discord-test:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message to Discord
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": "✅ GitHub Actions와 Discord Webhook 연결 테스트 성공!",
                 "username": "GitHub Action Bot"
               }' \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"
