name: Discord Solve Commit Notify

on: [push]

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      - name: Check commit message for 'solve'
        id: check
        run: |
          if echo "${{ github.event.head_commit.message }}" | grep -iq "solve"; then
            echo "found=true" >> $GITHUB_OUTPUT
          else
            echo "found=false" >> $GITHUB_OUTPUT
          fi

      - name: Send Discord notification
        if: steps.check.outputs.found == 'true'
        run: |
          curl -H "Content-Type: application/json" \
               -X POST \
               -d '{
                 "content": "✅ ${{ github.actor }} just completed an APS!\n`${{ github.event.head_commit.message }}`",
                 "username": "Github Action Bot"
               }' \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"
