- name: Send Discord Notification
  if: steps.check.outputs.found == 'true'
  uses: dawidd6/action-discord@v2
  with:
    webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
    content: "🧩 New solve commit pushed by ${{ github.actor }}: `${{ github.event.head_commit.message }}`"
